config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - lightning_core
    - media
third_party_settings:
  lightning_core:
    description: 'A view mode for use with the Media library and administrative views.'
id: media.media_browser
label: 'Media Browser'
targetEntityType: media
cache: true
