config_rewrite: replace
langcode: en
status: true
dependencies: {  }
name: medium
label: 'Medium (350Ã—350)'
effects:
  bddf0d06-42f9-4c75-a700-a33cafa25ea0:
    uuid: bddf0d06-42f9-4c75-a700-a33cafa25ea0
    id: image_scale
    weight: 0
    data:
      width: 350
      height: 350
      upscale: false
