third_party_settings:
  panelizer:
    enable: true
    custom: true
    displays:
      default:
        blocks:
          bc396094-60e7-49da-8b05-5fa3d0eb4083:
            id: 'entity_field:node:title'
            label: Title
            provider: ctools_block
            label_display: '0'
            formatter:
              label: hidden
              type: string
              settings:
                link_to_entity: false
              third_party_settings: {  }
              weight: 0
            context_mapping:
              entity: '@panelizer.entity_context:entity'
            region: middle
            uuid: bc396094-60e7-49da-8b05-5fa3d0eb4083
            weight: 1
        id: panels_variant
        uuid: 66454ba9-dca2-4264-bd09-9beeb133bd80
        label: ''
        weight: 0
        layout: foundation_1col
        layout_settings: {  }
        page_title: '[node:title]'
        storage_type: panelizer_default
        storage_id: 'node:landing_page:full:default'
        builder: ipe
content:
  workbench_moderation_control:
    weight: -20
    settings: {  }
    third_party_settings: {  }
