dependencies:
  module:
    - focal_point
content:
  image:
    type: image_focal_point
    weight: 0
    settings:
      preview_image_style: medium
      preview_link: true
      offsets: '50,50'
      progress_indicator: throbber
    third_party_settings:
      lightning_media:
        file_links: true
        remove_button: true
    region: content
